name: "Test"
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        ghc-version:
          - '8.8.3'
          - '8.8.4'
          - '8.10.1'
          - '8.10.2'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: ttuegel
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: Build
        run: nix-build --arg ghc-versions '[ "${{ matrix.ghc-version }}" ]'

      - name: Clean up cache
        run: nix-collect-garbage -d
