name: "Test"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          # Avoid cloning a detached-HEAD repository on pull_request events.
          # git-auto-commit-action (below) needs this to find the original
          # branch where it should push the changes.
          ref: ${{ github.head_ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: ttuegel
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: Materialize
        run: ./rematerialize.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: 'Materialize Nix expressions'
          file_pattern: '*.nix.d/'

      - name: Build
        run: nix-build
